#!/usr/bin/env bash
curl -o ./code/data/classification/config.yaml https://raw.githubusercontent.com/wangssuming/adlhw2_model/master/part2/config.yaml
curl -o ./code/data/classification/char.pkl https://raw.githubusercontent.com/wangssuming/adlhw2_model/master/part2/char.pkl
curl -o ./code/data/classification/word.pkl https://raw.githubusercontent.com/wangssuming/adlhw2_model/master/part2/word.pkl
curl -o ./code/data/classification/test.csv https://raw.githubusercontent.com/wangssuming/adlhw2_model/master/part2/test.csv
curl -o ./code/data/model/MODEL_NAME/ckpts/predict1.ckpt https://raw.githubusercontent.com/wangssuming/adlhw2_model/master/part2/predict1.ckpt
curl -o ./code/data/model/MODEL_NAME/ckpts/predict2.ckpt https://raw.githubusercontent.com/wangssuming/adlhw2_model/master/part2/predict2.ckpt
curl -o ./code/data/model/MODEL_NAME/ckpts/predict3.ckpt https://raw.githubusercontent.com/wangssuming/adlhw2_model/master/part2/predict3.ckpt
curl -o ./code/data/model/MODEL_NAME/ckpts/predict4.ckpt https://raw.githubusercontent.com/wangssuming/adlhw2_model/master/part2/predict4.ckpt
curl -o ./code/data/model/MODEL_NAME/ckpts/predict5.ckpt https://raw.githubusercontent.com/wangssuming/adlhw2_model/master/part2/predict5.ckpt
curl -o ./code/data/model/MODEL_NAME/ckpts/predict6.ckpt https://raw.githubusercontent.com/wangssuming/adlhw2_model/master/part2/predict6.ckpt
curl -o ./code/data/model/MODEL_NAME/ckpts/predict7.ckpt https://raw.githubusercontent.com/wangssuming/adlhw2_model/master/part2/predict7.ckpt
curl -o ./code/data/model/MODEL_NAME/config1.yaml https://raw.githubusercontent.com/wangssuming/adlhw2_model/master/part2/config1.yaml
curl -o ./code/data/model/MODEL_NAME/config2.yaml https://raw.githubusercontent.com/wangssuming/adlhw2_model/master/part2/config2.yaml
curl -o ./code/data/model/MODEL_NAME/config3.yaml https://raw.githubusercontent.com/wangssuming/adlhw2_model/master/part2/config3.yaml
curl -o ./code/data/model/MODEL_NAME/config4.yaml https://raw.githubusercontent.com/wangssuming/adlhw2_model/master/part2/config4.yaml
curl -o ./code/data/model/MODEL_NAME/config5.yaml https://raw.githubusercontent.com/wangssuming/adlhw2_model/master/part2/config5.yaml
curl -o ./code/data/model/MODEL_NAME/config6.yaml https://raw.githubusercontent.com/wangssuming/adlhw2_model/master/part2/config6.yaml
curl -o ./code/data/model/MODEL_NAME/config7.yaml https://raw.githubusercontent.com/wangssuming/adlhw2_model/master/part2/config7.yaml